export type DadJoke = {
  setup: string;
  punchline: string;
};

/** Clean, family-friendly dad jokes — one picked per calendar day (America/New_York). */
export const DAD_JOKES: DadJoke[] = [
  { setup: "Why don't scientists trust atoms?", punchline: "Because they make up everything." },
  { setup: "What do you call a fake noodle?", punchline: "An impasta." },
  { setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field." },
  { setup: "What do you call cheese that isn't yours?", punchline: "Nacho cheese." },
  { setup: "Why couldn't the bicycle stand up by itself?", punchline: "It was two tired." },
  { setup: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
  { setup: "Why don't eggs tell jokes?", punchline: "They'd crack each other up." },
  { setup: "What did the ocean say to the beach?", punchline: "Nothing — it just waved." },
  { setup: "Why did the math book look sad?", punchline: "It had too many problems." },
  { setup: "What do you call a factory that makes okay products?", punchline: "A satisfactory." },
  { setup: "Why did the coffee file a police report?", punchline: "It got mugged." },
  { setup: "What do you call a fish wearing a bowtie?", punchline: "So-fish-ticated." },
  { setup: "Why don't skeletons fight each other?", punchline: "They don't have the guts." },
  { setup: "What did one wall say to the other?", punchline: "I'll meet you at the corner." },
  { setup: "Why did the golfer bring two pairs of pants?", punchline: "In case he got a hole in one." },
  { setup: "What do you call a can opener that doesn't work?", punchline: "A can't opener." },
  { setup: "Why did the picture go to jail?", punchline: "It was framed." },
  { setup: "What do you call a dinosaur that crashes his car?", punchline: "Tyrannosaurus wrecks." },
  { setup: "Why did the tomato turn red?", punchline: "Because it saw the salad dressing." },
  { setup: "What do you call a sleeping bull?", punchline: "A bulldozer." },
  { setup: "Why can't your nose be 12 inches long?", punchline: "Because then it would be a foot." },
  { setup: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!" },
  { setup: "Why did the cookie go to the doctor?", punchline: "Because it felt crummy." },
  { setup: "What do you call a belt made of watches?", punchline: "A waist of time." },
  { setup: "Why did the stadium get hot after the game?", punchline: "All the fans left." },
  { setup: "What do you call a boomerang that won't come back?", punchline: "A stick." },
  { setup: "Why did the invisible man turn down the job offer?", punchline: "He couldn't see himself doing it." },
  { setup: "What do you call a pig that does karate?", punchline: "A pork chop." },
  { setup: "Why don't oysters donate to charity?", punchline: "Because they're shellfish." },
  { setup: "What did the grape do when it got stepped on?", punchline: "Nothing — it just let out a little wine." },
  { setup: "What do you call a lazy kangaroo?", punchline: "A pouch potato." },
  { setup: "Why did the computer go to the doctor?", punchline: "It had a virus." },
  { setup: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman." },
  { setup: "Why did the banana go to the doctor?", punchline: "Because it wasn't peeling well." },
  { setup: "What do you call a dog magician?", punchline: "A labracadabrador." },
  { setup: "Why did the chicken join a band?", punchline: "Because it had the drumsticks." },
  { setup: "What do you call a pile of cats?", punchline: "A meowtain." },
  { setup: "Why don't scientists trust stairs?", punchline: "Because they're always up to something." },
  { setup: "What did the left eye say to the right eye?", punchline: "Between you and me, something smells." },
  { setup: "Why did the calendar get popular?", punchline: "It had a lot of dates." },
  { setup: "What do you call a bear in the rain?", punchline: "A drizzly bear." },
  { setup: "Why did the student eat his homework?", punchline: "Because the teacher said it was a piece of cake." },
  { setup: "What do you call a fish with no eyes?", punchline: "A fsh." },
  { setup: "Why did the man put his money in the freezer?", punchline: "He wanted cold hard cash." },
  { setup: "What do you call a cow with no legs?", punchline: "Ground beef." },
  { setup: "Why did the light bulb fail school?", punchline: "It wasn't very bright." },
  { setup: "What do you call a rabbit with fleas?", punchline: "Bugs Bunny." },
  { setup: "Why did the kid bring a ladder to school?", punchline: "Because he wanted to go to high school." },
  { setup: "What do you call a cow that plays an instrument?", punchline: "A moo-sician." },
  { setup: "Why did the belt go to jail?", punchline: "It held up a pair of pants." },
  { setup: "What do you call a deer with no eyes?", punchline: "No idea." },
  { setup: "Why did the football coach go to the bank?", punchline: "To get his quarter back." },
  { setup: "What do you call a nosy pepper?", punchline: "Jalapeño business." },
  { setup: "Why did the duck get a standing ovation?", punchline: "It was a quack performance." },
  { setup: "What do you call a bee that can't make up its mind?", punchline: "A maybe." },
  { setup: "Why did the computer keep sneezing?", punchline: "It had a byte." },
  { setup: "What do you call a sad strawberry?", punchline: "A blueberry." },
  { setup: "What do you call a duck that gets all A's?", punchline: "A wise quacker." },
  { setup: "Why did the pillow go to school?", punchline: "To learn how to rest its case." },
  { setup: "What do you call a cat on the beach?", punchline: "Sandy claws." },
  { setup: "Why did the broom get promoted?", punchline: "It swept the competition." },
  { setup: "What do you call a sleeping dinosaur?", punchline: "A dino-snore." },
  { setup: "Why did the baker go to jail?", punchline: "He kneaded dough." },
  { setup: "What do you call a fish that sings?", punchline: "A tuna." },
  { setup: "Why did the clock get kicked out of class?", punchline: "It tocked too much." },
  { setup: "What do you call a cow in an earthquake?", punchline: "A milkshake." },
  { setup: "Why did the pencil cross the road?", punchline: "To draw attention." },
  { setup: "What do you call a monkey in a minefield?", punchline: "A baboom." },
  { setup: "Why did the sun go to school?", punchline: "To get a little brighter." },
  { setup: "What do you call a dog that picks locks?", punchline: "A corg-key." },
  { setup: "Why did the tree go to the dentist?", punchline: "To get a root canal." },
  { setup: "Why did the frog take the bus?", punchline: "His car got toad away." },
  { setup: "What do you call a sheep with no legs?", punchline: "A cloud." },
  { setup: "Why did the music teacher need a ladder?", punchline: "To reach the high notes." },
  { setup: "What do you call an alligator in a vest?", punchline: "An investigator." },
  { setup: "Why did the robot go on vacation?", punchline: "To recharge its batteries." },
  { setup: "What do you call a horse that lives next door?", punchline: "A neigh-bor." },
  { setup: "Why did the squirrel get good grades?", punchline: "It was nuts about learning." },
  { setup: "What do you call a ghost's true love?", punchline: "His ghoul-friend." },
  { setup: "Why did the bread go to therapy?", punchline: "It had too many loaves to carry." },
  { setup: "What do you call a fake stone in Ireland?", punchline: "A sham rock." },
  { setup: "Why did the chicken cross the playground?", punchline: "To get to the other slide." },
  { setup: "What do you call a train that sneezes?", punchline: "Achoo-choo train." },
  { setup: "Why did the librarian get fired?", punchline: "She was booked for overdue jokes." },
  { setup: "What do you call a potato that's an optimist?", punchline: "An spec-tater." },
  { setup: "Why did the moon skip dinner?", punchline: "It was full." },
  { setup: "What do you call a group of musical whales?", punchline: "An orca-stra." },
  { setup: "Why did the shoe go to the party alone?", punchline: "It lost its sole mate." },
  { setup: "Why did the gardener plant light bulbs?", punchline: "He wanted a power plant." },
  { setup: "Why did the vampire subscribe to the newspaper?", punchline: "He heard it had great circulation." },
  { setup: "Why did the donut go to the dentist?", punchline: "It needed a filling." },
  { setup: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus." },
  { setup: "Why did the fisherman put peanut butter on his rod?", punchline: "To catch a jellyfish." },
  { setup: "What do you call a cow that can't moo?", punchline: "An udder failure." },
  { setup: "Why did the rope skip school?", punchline: "It was a little frayed." },
  { setup: "Why did the salad win the race?", punchline: "It was ahead of the dressing." },
  { setup: "Why did the chicken sit on the clock?", punchline: "It wanted to lay time." },
  { setup: "What do you call a bear with no ears?", punchline: "B." },
  { setup: "What do you call a snowman party?", punchline: "A snowball." },
  { setup: "What do you call a camel with no humps?", punchline: "Hump-free." },
  { setup: "Why did the kid study on an airplane?", punchline: "He wanted a higher education." },
  { setup: "Why did the banana go to the party?", punchline: "It was a-peeling." },
  { setup: "What do you call a dog that loves reading?", punchline: "A book hound." },
  { setup: "Why did the corn get an award?", punchline: "It was ear-resistible." },
  { setup: "What do you call a cow that tells jokes?", punchline: "A laughing stock." },
  { setup: "Why did the egg hide?", punchline: "It was a little chicken." },
  { setup: "Why did the mirror go to therapy?", punchline: "It couldn't face itself." },
  { setup: "Why did the tree get a job?", punchline: "It wanted to branch out." },
  { setup: "What do you call a lazy spider?", punchline: "A web browser." },
  { setup: "Why did the banana split?", punchline: "Because it couldn't handle the pressure." },
  { setup: "Why did the chicken go to the séance?", punchline: "To talk to the other side." },
  { setup: "Why did the tomato break up with the lettuce?", punchline: "It couldn't romaine faithful." },
  { setup: "Why did the cookie cry?", punchline: "Because its mom was a wafer so long." },
  { setup: "Why did the bread win the race?", punchline: "It was on a roll." },
  { setup: "Why did the egg cross the road?", punchline: "To get to the other side — sunny side up." },
  { setup: "What do you call a cow that loves to tell dad jokes?", punchline: "A moo-d comedian." },
  { setup: "Why did the pastor bring a ladder to church?", punchline: "He wanted to reach new heights." },
  { setup: "What do you call a Bible character who works out?", punchline: "A muscle prophet." },
  { setup: "Why did Noah do so well in school?", punchline: "He was always on the ark of success." },
  { setup: "What do you call a nervous church bell?", punchline: "A wrung-out ringer." },
  { setup: "Why did the hymn book go to the doctor?", punchline: "It had too many verses." },
  { setup: "What do you call a sheep that tells jokes?", punchline: "A baa-d comedian." },
  { setup: "Why did the candle go to church?", punchline: "It wanted to be a light unto the world." },
  { setup: "What do you call a fish that loves fellowship?", punchline: "A school of faith." },
  { setup: "Why did the coffee taste like mud?", punchline: "It was ground this morning." },
  { setup: "What do you call a belt made of watches?", punchline: "A waist of time." },
  { setup: "Why did the grape stop in the middle of the road?", punchline: "It ran out of juice." },
  { setup: "What do you call a dog that loves the outdoors?", punchline: "A labrador retriever." },
  { setup: "Why did the football team go to the bakery?", punchline: "They needed a good roll model." },
  { setup: "What do you call a cow that plays hide and seek?", punchline: "A cow-ard." },
  { setup: "Why did the sponge go to school?", punchline: "It wanted to soak up knowledge." },
  { setup: "What do you call a fish that practices medicine?", punchline: "A sturgeon." },
  { setup: "Why did the duck get detention?", punchline: "It was quacking up in class." },
  { setup: "What do you call a dog that loves math?", punchline: "A labradorithm." },
  { setup: "Why did the pencil break up with the paper?", punchline: "It felt drawn away." },
  { setup: "What do you call a cow that tells fortunes?", punchline: "A moo-d reader." },
  { setup: "Why did the clock get grounded?", punchline: "It tocked back to its parents." },
  { setup: "What do you call a fish that wears a crown?", punchline: "A king fish." },
  { setup: "Why did the lamp break up with the outlet?", punchline: "There was no spark." },
  { setup: "What do you call a dog that loves gardening?", punchline: "A labrador retriever of weeds." },
  { setup: "Why did the tomato go to the party?", punchline: "It wanted to ketchup with friends." },
  { setup: "What do you call a cow that loves to dance?", punchline: "A moo-ver and shaker." },
  { setup: "Why did the egg get a promotion?", punchline: "It was an egg-cellent worker." },
  { setup: "What do you call a fish that loves to travel?", punchline: "A globe-trotter." },
  { setup: "Why did the cookie go to the gym?", punchline: "It wanted to get chip in shape." },
  { setup: "What do you call a cow that loves to cook?", punchline: "A chef-moo." },
  { setup: "Why did the grape get a job?", punchline: "It wanted to wine and dine." },
  { setup: "What do you call a dog that loves to swim?", punchline: "A labrador retriever of waves." },
  { setup: "What do you call a cow that loves to write?", punchline: "A moo-thor." },
  { setup: "Why did the clock go to the party?", punchline: "It wanted to have a good time." },
  { setup: "What do you call a fish that loves to dance?", punchline: "A tuna turner." },
  { setup: "Why did the bread go to the doctor?", punchline: "It was feeling crumby." },
  { setup: "What do you call a cow that loves to run?", punchline: "A moo-marathoner." },
  { setup: "Why did the egg go to school?", punchline: "To get egg-ucated." },
  { setup: "Why did the tomato get a ticket?", punchline: "It ran a red light." },
  { setup: "What do you call a cow that loves to fish?", punchline: "A moo-angler." },
  { setup: "What do you call a fish that loves to read?", punchline: "A bookworm fish." },
  { setup: "What do you call a cow that loves to hike?", punchline: "A trail moo-er." },
  { setup: "What do you call a dog that loves to cook?", punchline: "A labrador retriever of recipes." },
  { setup: "What do you call a cow that loves to camp?", punchline: "A happy camper-moo." },
  { setup: "What do you call a fish that loves to sing?", punchline: "A tuna fish." },
  { setup: "Why did the grape go to school?", punchline: "It wanted to be raisin the bar." },
  { setup: "What do you call a cow that loves to knit?", punchline: "A moo-ter." },
  { setup: "What do you call a fish that loves to play sports?", punchline: "A sporty fish." },
  { setup: "What do you call a cow that loves to tell stories?", punchline: "A moo-th teller." },
  { setup: "What do you call a cow that loves to play chess?", punchline: "A check-moo." },
  { setup: "What do you call a fish that loves to bake?", punchline: "A baker fish." },
  { setup: "What do you call a cow that loves to play guitar?", punchline: "A moo-sician." },
  { setup: "What do you call a fish that loves to garden?", punchline: "A green fish." },
  { setup: "What do you call a cow that loves to paint?", punchline: "An artiste-moo." },
  { setup: "What do you call a fish that loves to camp?", punchline: "A camper fish." },
  { setup: "What do you call a cow that loves to sing?", punchline: "A moo-sical talent." },
  { setup: "What do you call a fish that loves to write?", punchline: "A writer fish." },
  { setup: "What do you call a cow that loves to read?", punchline: "A book moo-k." },
  { setup: "What do you call a fish that loves to cook?", punchline: "A chef fish." },
  { setup: "What do you call a cow that loves to tell dad jokes?", punchline: "A moo-d comedian." },
];

function hashDateKey(dateKey: string): number {
  let hash = 0;
  for (let i = 0; i < dateKey.length; i++) {
    hash = (hash * 31 + dateKey.charCodeAt(i)) >>> 0;
  }
  return hash;
}

/** Same joke for everyone on a given calendar day (America/New_York). */
export function getDailyDadJoke(date = new Date()): DadJoke {
  const dateKey = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/New_York",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);

  const index = hashDateKey(dateKey) % DAD_JOKES.length;
  return DAD_JOKES[index]!;
}

export function getDailyDadJokeLabel(date = new Date()): string {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "America/New_York",
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(date);
}
